# Generated by Django 5.1.1 on 2024-09-29 09:01

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='icones')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(help_text='Digite o CPF no formato xxx.xxx.xxx-xx', max_length=14, unique=True, validators=[authentication.validators.validar_cpf])),
                ('data_nasc', models.DateField()),
                ('telefone_contato', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('funcao', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('historico_funcoes', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, max_length=2000, null=True)),
                ('add_matricula', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('senha', models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True)),
            ],
        ),
    ]
